# Generated by Django 4.0.2 on 2023-04-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='price',
            new_name='salary',
        ),
    ]
