# Generated by Django 4.0.2 on 2023-04-11 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_price_post_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='uploads')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='core.post')),
            ],
        ),
    ]
