# Generated by Django 4.0.2 on 2023-04-11 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobApplies', to=settings.AUTH_USER_MODEL)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobApplies', to='core.cv')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobApplies', to='core.post')),
            ],
        ),
    ]
