# Generated by Django 4.0.2 on 2023-04-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobapplied'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplied',
            options={'verbose_name_plural': 'Job Applies'},
        ),
    ]
