# Generated by Django 4.0.2 on 2023-05-30 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_jobapplied_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='cv',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='core.post'),
        ),
    ]
